openapi: 3.0.0
info:
  version: 0.0.1
  title:  openapi components

components:
  securitySchemes:
    jwt:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://localhost:3000/signin
          scopes:
            api:access: API access
