openapi: 3.0.2
info:
  version: 0.0.1
  title: '@viron/example-nodejs ping'
  description: ping api specifications

tags:
  - name: ping

paths:
  /ping:
    get:
      operationId: getPing
      tags:
        - ping
      summary: ping
      description: 死活監視
      x-skip-auditlog: true
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: pong
