openapi: 3.0.0
info:
  version: 0.0.1
  title: viron example nodejs
  description: viron example node.js api specifications

servers:
  - url: /

tags:
  - name: ping

paths:
  '/ping':
    get:
      operationId: 'getPing'
      tags:
        - ping
      summary: ping
      description: 死活監視
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: pong

components:
  securitySchemes:
    jwt:
      $ref: './components.yaml#/components/securitySchemes/jwt'
