openapi: 3.0.2
info:
  version: 0.0.1
  title: '@viron/example-nodejs users'
  description: users api specifications

tags:
  - name: root

paths:
  /:
    get:
      operationId: getRoot
      tags:
        - root
      summary: redirect to /oas
      description: /oas へリダイレクト
      responses:
        301:
          description: OK
