openapi: 3.0.2
info:
  version: 0.0.1
  title: '@viron/example-nodejs'
  description: api specifications

servers:
  - url: /

tags:
  - name: root

paths:
  /:
    get:
      operationId: getRoot
      tags:
        - root
      summary: redirect to /oas
      description: /oas へリダイレクト
      parameters:
        - $ref: './components.yaml#/components/parameters/AuthorizationHeaderParam'
      responses:
        301:
          description: OK
      security:
        - jwt: []