version: '3.8'

services:

  example:
    build: 
      context: '.'
      dockerfile: Dockerfile.example-nodejs
    restart: always
    depends_on:
      - mongo
    ports:
      - 3000:3000
      - 9229:9229 # node-inspector
    environment:
      - MODE=mongo
    volumes:
      - $PWD/example/nodejs/package.json:/viron/example/nodejs/package.json
      - $PWD/example/nodejs/src:/viron/example/nodejs/src
      - $PWD/packages/nodejs:/viron/packages/nodejs
    command: npm run dev

  mongo:
    extends:
      file: example/nodejs/docker-compose.mongo.yml
      service: mongo
