openapi: 3.0.2
info:
  version: 0.0.1
  title: '@viron/lib authconfigs'
  description: authconfigs api specifications

tags:
  - name: vironAuthConfig

paths:
  /viron/authconfigs:
    get:
      operationId: listVironAuthconfigs
      tags:
        - vironAuthConfig
      summary: list auth configs
      description: 認証設定を取得する
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VironAuthConfigListWithPager'

components:
  schemas:
    VironAuthConfigListWithPager:
      allOf:
        - $ref: './components.yaml#/components/schemas/Pager'
        - type: object
          properties:
            list:
              $ref: '#/components/schemas/VironAuthConfigList'
          required:
            - list

    VironAuthConfigList:
      type: array
      items:
        $ref: '#/components/schemas/VironAuthConfig'

    VironAuthConfig:
      type: object
      properties:
        provider:
          description: 認証プロバイダ
          type: string
          example: google
        type:
          description: 認証方式
          type: string
          enum:
            - email
            - oauth
            - signout
          example: oauth
        pathObject:
          description: OASのPathsObject
          type: object
          patternProperties:
            '^/':
              $ref: '#/components/schemas/VironAuthConfigPathItem'
      required:
        - provider
        - type
        - pathObject

    # @Reference https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.0/schema.json
    VironAuthConfigPathItem:
      type: object
      patternProperties:
        '^(get|put|post|delete)$':
          $ref: '#/components/schemas/VironAuthConfigOperation'

    VironAuthConfigOperation:
      type: object
      properties:
        tags:
          type: array
          items:
            type: string
        summary:
          type: string
        description:
          type: string
        externalDocs:
          '$ref': '#/components/schemas/VironAuthConfigExternalDocumentation'
        operationId:
          type: string
        parameters:
          type: array
          items:
            oneOf:
              - '$ref': '#/components/schemas/VironAuthConfigParameter'
              - '$ref': '#/components/schemas/VironAuthConfigReference'
          uniqueItems: true
        requestBody:
          oneOf:
            - '$ref': '#/components/schemas/VironAuthConfigRequestBody'
            - '$ref': '#/components/schemas/VironAuthConfigReference'
        responses:
          '$ref': '#/components/schemas/VironAuthConfigResponses'
        deprecated:
          type: boolean
          default: false
        security:
          type: array
          items:
            '$ref': '#/components/schemas/VironAuthConfigSecurityRequirement'
      patternProperties:
        '^x-': {}
      additionalProperties: false
      required:
        - responses

    VironAuthConfigExternalDocumentation:
      type: object
      required:
        - url
      properties:
        description:
          type: string
        url:
          type: string
          format: uri-reference
      patternProperties:
        '^x-': {}
      additionalProperties: false

    VironAuthConfigParameter:
      type: object
      properties:
        name:
          type: string
        in:
          type: string
        description:
          type: string
        required:
          type: boolean
          default: false
        deprecated:
          type: boolean
          default: false
        allowEmptyValue:
          type: boolean
          default: false
        style:
          type: string
        explode:
          type: boolean
        allowReserved:
          type: boolean
          default: false
        schema:
          oneOf:
            - '$ref': '#/components/schemas/VironAuthConfigSchema'
            - '$ref': '#/components/schemas/VironAuthConfigReference'
        content:
          type: object
          additionalProperties:
            '$ref': '#/components/schemas/VironAuthConfigMediaType'
          minProperties: 1
          maxProperties: 1
        example: {}
        examples:
          type: object
          additionalProperties:
            oneOf:
              - '$ref': '#/components/schemas/VironAuthConfigExample'
              - '$ref': '#/components/schemas/VironAuthConfigReference'
      patternProperties:
        '^x-': {}
      additionalProperties: false
      required:
        - name
        - in
      allOf:
        - '$ref': '#/components/schemas/VironAuthConfigExampleXORExamples'
        - '$ref': '#/components/schemas/VironAuthConfigSchemaXORContent'
        - '$ref': '#/components/schemas/VironAuthConfigParameterLocation'

    VironAuthConfigMediaType:
      type: object
      properties:
        schema:
          oneOf:
            - '$ref': '#/components/schemas/VironAuthConfigSchema'
            - '$ref': '#/components/schemas/VironAuthConfigReference'
        example: {}
        examples:
          type: object
          additionalProperties:
            oneOf:
              - '$ref': '#/components/schemas/VironAuthConfigExample'
              - '$ref': '#/components/schemas/VironAuthConfigReference'
        encoding:
          type: object
          additionalProperties:
            '$ref': '#/components/schemas/VironAuthConfigEncoding'
      patternProperties:
        '^x-': {}
      additionalProperties: false
      allOf:
        - '$ref': '#/components/schemas/VironAuthConfigExampleXORExamples'

    VironAuthConfigEncoding:
      type: object
      properties:
        contentType:
          type: string
        headers:
          type: object
          additionalProperties:
            '$ref': '#/components/schemas/VironAuthConfigHeader'
        style:
          type: string
          enum:
            - form
            - spaceDelimited
            - pipeDelimited
            - deepObject
        explode:
          type: boolean
        allowReserved:
          type: boolean
          default: false
      additionalProperties: false

    VironAuthConfigHeader:
      type: object
      properties:
        description:
          type: string
        required:
          type: boolean
          default: false
        deprecated:
          type: boolean
          default: false
        allowEmptyValue:
          type: boolean
          default: false
        style:
          type: string
          enum:
            - simple
          default: simple
        explode:
          type: boolean
        allowReserved:
          type: boolean
          default: false
        schema:
          oneOf:
            - '$ref': '#/components/schemas/VironAuthConfigSchema'
            - '$ref': '#/components/schemas/VironAuthConfigReference'
        example: {}
        examples:
          type: object
          additionalProperties:
            oneOf:
              - '$ref': '#/components/schemas/VironAuthConfigExample'
              - '$ref': '#/components/schemas/VironAuthConfigReference'
      patternProperties:
        '^x-': {}
      additionalProperties: false
      allOf:
        - '$ref': '#/components/schemas/VironAuthConfigExampleXORExamples'
        - '$ref': '#/components/schemas/VironAuthConfigSchemaXORContent'

    VironAuthConfigExample:
      type: object
      properties:
        summary:
          type: string
        description:
          type: string
        value: {}
        externalValue:
          type: string
          format: uri-reference
      patternProperties:
        '^x-': {}
      additionalProperties: false

    VironAuthConfigExampleXORExamples:
      description: Example and examples are mutually exclusive
      not:
        required:
          - example
          - examples

    VironAuthConfigSchemaXORContent:
      description: Schema and content are mutually exclusive, at least one is required
      not:
        required:
          - schema
          - content
      oneOf:
        - required:
            - schema
        - required:
            - content
          description: Some properties are not allowed if content is present
          allOf:
            - not:
                required:
                  - style
            - not:
                required:
                  - explode
            - not:
                required:
                  - allowReserved
            - not:
                required:
                  - example
            - not:
                required:
                  - examples

    VironAuthConfigParameterLocation:
      description: Parameter location
      oneOf:
        - description: Parameter in path
          required:
            - required
          properties:
            in:
              enum:
                - path
            style:
              enum:
                - matrix
                - label
                - simple
              default: simple
            required:
              enum:
                - true
        - description: Parameter in query
          properties:
            in:
              enum:
                - query
            style:
              enum:
                - form
                - spaceDelimited
                - pipeDelimited
                - deepObject
              default: form
        - description: Parameter in header
          properties:
            in:
              enum:
                - header
            style:
              enum:
                - simple
              default: simple
        - description: Parameter in cookie
          properties:
            in:
              enum:
                - cookie
            style:
              enum:
                - form
              default: form

    VironAuthConfigReference:
      type: object
      required:
        - '$ref'
      patternProperties:
        '^\\$ref$':
          type: string
          format: uri-reference

    VironAuthConfigRequestBody:
      type: object
      required:
        - content
      properties:
        description:
          type: string
        content:
          type: object
          additionalProperties:
            '$ref': '#/components/schemas/VironAuthConfigMediaType'
        required:
          type: boolean
          default: false
      patternProperties:
        '^x-': {}
      additionalProperties: false

    VironAuthConfigResponses:
      type: object
      properties:
        default:
          oneOf:
            - '$ref': '#/components/schemas/VironAuthConfigResponse'
            - '$ref': '#/components/schemas/VironAuthConfigReference'
      patternProperties:
        '^[1-5](?:\\d{2}|XX)$':
          oneOf:
            - '$ref': '#/components/schemas/VironAuthConfigResponse'
            - '$ref': '#/components/schemas/VironAuthConfigReference'
        '^x-': {}
      minProperties: 1
      additionalProperties: false

    VironAuthConfigResponse:
      type: object
      required:
        - description
      properties:
        description:
          type: string
        headers:
          type: object
          additionalProperties:
            oneOf:
              - '$ref': '#/components/schemas/VironAuthConfigHeader'
              - '$ref': '#/components/schemas/VironAuthConfigReference'
        content:
          type: object
          additionalProperties:
            '$ref': '#/components/schemas/VironAuthConfigMediaType'
      patternProperties:
        '^x-': {}
      additionalProperties: false

    VironAuthConfigSecurityRequirement:
      type: object
      additionalProperties:
        type: array
        items:
          type: string

    VironAuthConfigSchema:
      type: object
      properties:
        title:
          type: string
        multipleOf:
          type: number
          minimum: 0
        maximum:
          type: number
        exclusiveMaximum:
          type: boolean
          default: false
        minimum:
          type: number
        exclusiveMinimum:
          type: boolean
          default: false
        maxLength:
          type: integer
          minimum: 0
        minLength:
          type: integer
          minimum: 0
          default: 0
        pattern:
          type: string
          format: regex
        maxItems:
          type: integer
          minimum: 0
        minItems:
          type: integer
          minimum: 0
          default: 0
        uniqueItems:
          type: boolean
          default: false
        maxProperties:
          type: integer
          minimum: 0
        minProperties:
          type: integer
          minimum: 0
          default: 0
        required:
          type: array
          items:
            type: string
          minItems: 1
          uniqueItems: true
        enum:
          type: array
          items: {}
          minItems: 1
          uniqueItems: false
        type:
          type: string
          enum:
            - array
            - boolean
            - integer
            - number
            - object
            - string
        not:
          '$ref': '#/components/schemas/VironAuthConfigReference'
        allOf:
          type: array
          items:
            '$ref': '#/components/schemas/VironAuthConfigReference'
        oneOf:
          type: array
          items:
            '$ref': '#/components/schemas/VironAuthConfigReference'
        anyOf:
          type: array
          items:
            '$ref': '#/components/schemas/VironAuthConfigReference'
        items:
          '$ref': '#/components/schemas/VironAuthConfigReference'
        properties:
          type: object
          additionalProperties:
            '$ref': '#/components/schemas/VironAuthConfigReference'
        additionalProperties:
          oneOf:
            - '$ref': '#/components/schemas/VironAuthConfigReference'
            - type: boolean
          default: true
        description:
          type: string
        format:
          type: string
        default: {}
        nullable:
          type: boolean
          default: false
        discriminator:
          '$ref': '#/components/schemas/VironAuthConfigDiscriminator'
        readOnly:
          type: boolean
          default: false
        writeOnly:
          type: boolean
          default: false
        example: {}
        externalDocs:
          '$ref': '#/components/schemas/VironAuthConfigExternalDocumentation'
        deprecated:
          type: boolean
          default: false
        xml:
          '$ref': '#/components/schemas/VironAuthConfigXML'
      patternProperties:
        '^x-': {}
      additionalProperties: false

    VironAuthConfigDiscriminator:
      type: object
      required:
        - propertyName
      properties:
        propertyName:
          type: string
        mapping:
          type: object
          additionalProperties:
            type: string

    VironAuthConfigXML:
      type: object
      properties:
        name:
          type: string
        namespace:
          type: string
          format: uri
        prefix:
          type: string
        attribute:
          type: boolean
          default: false
        wrapped:
          type: boolean
          default: false
      patternProperties:
        '^x-': {}
      additionalProperties: false
