openapi: 3.0.2
info:
  version: 0.0.1
  title: '@viron/lib authtypes'
  description: authtypes api specifications

tags:
  - name: vironAuthType

paths:
  /viron/authtypes:
    get:
      operationId: listVironAuthtypes
      tags:
        - vironAuthType
      summary: list auth types
      description: 認証方式一覧
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VironAuthTypeListWithPager'

components:
  schemas:
    VironAuthTypeListWithPager:
      allOf:
        - $ref: './components.yaml#/components/schemas/Pager'
        - type: object
          properties:
            list:
              $ref: '#/components/schemas/VironAuthTypeList'
          required:
            - list

    VironAuthTypeList:
      type: array
      items:
        $ref: '#/components/schemas/VironAuthType'

    VironAuthType:
      type: object
      properties:
        provider:
          description: 認証プロバイダ
          type: string
          example: google
        type:
          description: 認証方式
          type: string
          enum:
            - email
            - oauth
            - signout
          example: oauth
        method:
          description: リクエストメソッド
          type: string
          enum:
            - GET
            - POST
            - PUT
          example: POST
        url:
          description: リクエストURL
          type: string
          example: '/google/signin'
      required:
        - provider
        - type
        - method
        - url
