openapi: 3.0.2
info:
  version: 0.0.1
  title: '@viron/lib oas'
  description: oas api specifications
  # pagerとsortの仕様定義
  x-table-pager:
    pager-req-page-key: page # ページ番号を指定するクエリパラメータ
    pager-req-size-key: size # ページサイズを指定するクエリパラメータ
    pager-resp-maxpage-key: maxPage # 最大ページ数を返すキー
    pager-resp-page-key: currentPage # 現在のページ番号を返すキー
  x-table-sort:
    sort-req-key: sort # ソートを指定するクエリパラメータ
    sort-resp-key: list # リストデータを返すキー

tags:
  - name: oas

paths:
  /oas:
    get:
      operationId: getOas
      tags:
        - oas
      summary: get oas
      description: OpenAPI Specification の取得
      parameters:
        - $ref: './components.yaml#/components/parameters/AuthorizationHeaderParam'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                example: {}
      security:
        - jwt: []

components:
  securitySchemes:
    jwt:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://localhost:3000/signin
          scopes:
            api:access: API access