openapi: 3.0.2
info:
  version: 0.0.1
  title: '@viron/example-nodejs viron'
  description: viron api specifications

tags:
  - name: viron

paths:
  /viron:
    get:
      operationId: getViron
      tags:
        - viron
      summary: get viron settings
      description: viron全体設定の取得
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Viron'
      security:
        - jwt: []

components:
  schemas:
    Viron:
      type: object
      properties:
        color:
          default: white
          enum:
            - white
            - black
            - purple
            - blue
            - green
            - yellow
            - red
            - gray
          type: string
          example: white
        theme:
          default: standard
          enum:
            - standard
            - midnight
            - terminal
          type: string
          example: standard
        name:
          type: string
          example: Viron Demo
        pages:
          items:
            $ref: '#/components/schemas/VironPage'
          type: array
        thumbnail:
          type: string
          example: https://example.com/thumb.png
        tags:
          items:
            type: string
            example: example
          type: array
      required:
        - color
        - theme
        - name
        - pages
        - thumbnail
        - tags

    VironPage:
      type: object
      properties:
        id:
          description: ページID
          type: string
          example: user
        group:
          type: string
          example: UserGroup
        name:
          description: 名称
          type: string
          example: ユーザー
        section:
          description: セクション名
          default: manage
          enum:
            - manage
            - dashboard
          type: string
          example: admin
        components:
          items:
            $ref: '#/components/schemas/VironComponent'
          type: array
      required:
        - id
        - group
        - name
        - section
        - components

    VironComponent:
      type: object
      properties:
        api:
          $ref: '#/components/schemas/VironComponentApi'
        name:
          description: コンポーネント名
          type: string
          example: ユーザー
        style:
          description: コンポーネントスタイル
          type: string
          default: number
          enum:
            - number
            - table
            - explorer
            - list
            - chart
          example: table
        pagination:
          description: ページネーション
          type: boolean
          example: true
        primary:
          description: 主キー
          type: string
        query:
          description: クエリパラメータ
          type: array
          items:
            $ref: '#/components/schemas/VironComponentQuery'
        table_labels:
          description: テーブル列 表示順
          items:
            type: string
            example: id
          type: array
        actions:
          description: 関連するAPIのパス
          type: array
          items:
            type: string
        sort:
          description: ソートを有効にするキーのリスト
          type: array
          items:
            type: string
        auto_refresh_sec:
          description: 自動リロード間隔(秒)
          type: integer
          minimum: 3
        preview:
          $ref: '#/components/schemas/VironComponentPreview'
        options:
          description: オプション
          type: array
          items:
            $ref: '#/components/schemas/VironComponentOption'
      required:
        - api
        - name
        - style
        - pagination

    VironComponentApi:
      type: object
      properties:
        method:
          description: リクエストメソッド
          type: string
          example: get
        path:
          description: リクエストパス
          type: string
          example: /user
      required:
        - method
        - path

    VironComponentPreview:
      type: object
      properties:
        path:
          type: string
        method:
          type: string
          enum:
            - get
          default: get
        target:
          type: string
          default: _blank
      required:
        - path
        - method
        - target

    VironComponentOption:
      type: object
      properties:
        key:
          description: オプション キー名
          type: string
          example: key
        value:
          description: オプション 値
          type: string
          example: val
      required:
        - key
        - value

    VironComponentQuery:
      type: object
      properties:
        key:
          description: クエリパラメータ キー名
          type: string
          example: key
        type:
          default: string
          description: クエリパラメータ 型
          enum:
            - string
            - integer
            - number
            - boolean
            - date
            - datetime
            - time
          type: string
          example: string
      required:
        - key
        - type

  securitySchemes:
    jwt:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://localhost:3000/signin
          scopes:
            api:access: API access