apiVersion: v1
kind: Service
metadata:
  name: example
  namespace: viron-nodejs
spec:
  ports:
    - port: 3000
  type: LoadBalancer
  selector:
    app: example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: viron-nodejs
spec:
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: example
          image: viron/example/nodejs
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: example
