version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 14

  pre_build:
    commands:
      - echo Install packages...
      - cd ./packages/app
      - npm install --no-progress --legacy-peer-deps && npm cache verify
  build:
    commands:
      - echo Building app...
      - pwd
      - npm run build

  post_build:
    commands:
      - echo push step...
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$COMMIT_ID
      - docker push $REPOSITORY_URI:latest

artifacts:
  files:
    - packages/app/public
  name: viron-app-artifact
  discard-paths: no
