version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: latest

  pre_build:
    commands:
      - echo Install packages...
      - cd $CODEBUILD_SRC_DIR/packages/app
      - npm install --no-progress --legacy-peer-deps && npm cache verify

  build:
    commands:
      - echo Building app...
      - cd $CODEBUILD_SRC_DIR/packages/app
      - npm run build
      - cd $CODEBUILD_SRC_DIR
      - mv $CODEBUILD_SRC_DIR/packages/app/public .

artifacts:
  files:
    - '**/*'
  base-directory: public
  name: viron-app-artifact
  discard-paths: no
