version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: latest

  pre_build:
    commands:
      - echo Install packages...
      - npm install --no-progress
      - echo Building linter...
      - npm run build -w packages/linter

  build:
    commands:
      - echo Building app...
      - npm run build -w packages/app

artifacts:
  files:
    - codepipeline/app-deployspec.yml
    - packages/app/package.json
    - packages/app/public/**/*
    - packages/app/cypress.json
    - packages/app/cypress/**/*
  name: viron-app-artifact
  discard-paths: no
