version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: latest

  pre_build:
    commands:
      - echo Install packages...
      - cd ./packages/app
      - npm install --no-progress --legacy-peer-deps && npm cache verify
  build:
    commands:
      - echo Building app...
      - npm run build

artifacts:
  files:
    - packages/app/public
  name: viron-app-artifact
  discard-paths: no
