version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: latest

  pre_build:
    commands:
      - echo Install packages...
      - npm install --no-progress

  build:
    commands:
      - echo Building linter...
      - npm run build -w packages/linter -w packages/app
      - echo Building app...
      - npm run build:prefix -w packages/app


artifacts:
  files:
    - codepipeline/snapshot-app-deployspec.yml
    - packages/app/package.json
    - packages/app/public/**/*
  name: viron-snapshot-app-artifact
  discard-paths: no
