
version: '3.8'

services:

  example:
    build: .
    restart: always
    depends_on:
      - mongo
    ports:
      - 3000:3000
      - 9229:9229 # node-inspector
    environment:
      - MODE=mongo
    volumes:
      - $PWD/package.json:/example/nodejs/package.json
      - $PWD/src:/example/nodejs/src
    command: npm run dev

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - $PWD/data/mongo/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      default:
        aliases:
          - viron.example.nodejs