apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: example
build:
  local:
    push: false
    useBuildkit: true

  artifacts:
    - image: viron/example/nodejs
      docker:
        dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
      - k8s/*

portForward:
  - resourceType: deployment
    resourceName: example
    port: 9229
    localPort: 9229
