apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: example
build:
  local:
    push: false
    useBuildkit: true

  artifacts:
    - image: viron/example/nodejs
      docker:
        dockerfile: Dockerfile

profiles:
  - name: mysql
    activation:
      - env: mode=mysql
    deploy:
      kubectl:
        manifests:
          - k8s/comfigmap-mysql.yaml
          - k8s/deployment.yaml
          - k8s/deployment-mysql.yaml
  - name: mongo
    activation:
      - env: mode=mongo
    deploy:
      kubectl:
        manifests:
          - k8s/comfigmap-mongo.yaml
          - k8s/deployment.yaml
          - k8s/deployment-mongo.yaml

portForward:
  - resourceType: deployment
    resourceName: example
    port: 9229
    localPort: 9229
